#!/usr/bin/env python3
"""Minify web/home.js and web/home.css, then embed them into web_assets.h."""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEB = ROOT / "web"
OUT = ROOT / "web_assets.h"
HTML_TEMPLATE = WEB / "home.html"
JS_SOURCE = WEB / "home.js"
CSS_SOURCE = WEB / "home.css"
RAW_DELIMITER = "HTML"


def run_minifier(command: list[str], source: str) -> str | None:
    result = subprocess.run(
        command,
        input=source,
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    if result.returncode != 0:
        print(result.stderr.strip(), file=sys.stderr)
        return None

    output = result.stdout.strip()
    return output or None


def minify_js(source: str) -> str:
    if shutil.which("terser"):
        command = ["terser", "--compress", "--mangle"]
    elif shutil.which("npx"):
        command = ["npx", "--yes", "terser", "--compress", "--mangle"]
    else:
        command = None

    if command:
        minified = run_minifier(command, source)
        if minified:
            print("JS minified with terser.")
            return minified

    print("terser not available; using basic JS minifier.", file=sys.stderr)
    without_blocks = re.sub(r"/\*.*?\*/", "", source, flags=re.S)
    lines = []
    for line in without_blocks.splitlines():
        stripped = line.split("//", 1)[0].strip()
        if stripped:
            lines.append(stripped)
    return re.sub(r"\s+", " ", " ".join(lines)).strip()


def minify_css_basic(source: str) -> str:
    css = re.sub(r"/\*.*?\*/", "", source, flags=re.S)
    css = re.sub(r"\s+", " ", css).strip()
    # Tighten around structural characters only; spaces inside values (e.g.
    # calc(100vw - 28px), "1px solid") must be preserved.
    css = re.sub(r"\s*([{};,>])\s*", r"\1", css)
    css = re.sub(r";\}", "}", css)
    return css


def minify_css(source: str) -> str:
    if shutil.which("csso"):
        command = ["csso"]
    elif shutil.which("npx"):
        command = ["npx", "--yes", "csso-cli"]
    else:
        command = None

    if command:
        minified = run_minifier(command, source)
        if minified:
            print("CSS minified with csso.")
            return minified

    print("csso not available; using basic CSS minifier.", file=sys.stderr)
    return minify_css_basic(source)


def assert_safe_for_raw_string(content: str, label: str) -> None:
    token = f"){RAW_DELIMITER}\""
    if token in content:
        raise ValueError(f"{label} contains raw-string terminator {token!r}")


def build_home_page_html(minified_js: str, minified_css: str) -> str:
    template = HTML_TEMPLATE.read_text(encoding="utf-8")
    for placeholder in ("@@HOME_JS@@", "@@HOME_CSS@@"):
        if placeholder not in template:
            raise ValueError(f"web/home.html must contain {placeholder} placeholder")

    html = template.replace("@@HOME_CSS@@", minified_css)
    html = html.replace("@@HOME_JS@@", minified_js)
    assert_safe_for_raw_string(html, "home page HTML")
    return html


def write_header(home_page_html: str, js_bytes: int, css_bytes: int, html_bytes: int) -> None:
    header = f"""// Auto-generated by scripts/build_web_assets.py — do not edit.
// Rebuild after changing web/home.js, web/home.css, or web/home.html:
//   python3 scripts/build_web_assets.py

#pragma once

#include <Arduino.h>

const char HOME_PAGE_HTML[] PROGMEM = R"{RAW_DELIMITER}({home_page_html}){RAW_DELIMITER}";
"""
    OUT.write_text(header, encoding="utf-8")
    print(
        f"Wrote {OUT.name} ({html_bytes:,} bytes HTML total: "
        f"{js_bytes:,} bytes JS, {css_bytes:,} bytes CSS)"
    )


def main() -> int:
    for required in (JS_SOURCE, CSS_SOURCE, HTML_TEMPLATE):
        if not required.is_file():
            print(f"Missing {required}", file=sys.stderr)
            return 1

    minified_js = minify_js(JS_SOURCE.read_text(encoding="utf-8"))
    assert_safe_for_raw_string(minified_js, "minified JS")

    minified_css = minify_css(CSS_SOURCE.read_text(encoding="utf-8"))
    assert_safe_for_raw_string(minified_css, "minified CSS")

    home_page_html = build_home_page_html(minified_js, minified_css)
    write_header(
        home_page_html,
        len(minified_js.encode("utf-8")),
        len(minified_css.encode("utf-8")),
        len(home_page_html.encode("utf-8")),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
